# Workshop 1 - Environment Setting & Matrix Operations



## 1. Environment Setting

Useful Tools for this course.

#### 1. Conda Environment


#### 2. Jupyter notebook


#### 3. Numpy


#### 4. Sckit-learn




In [1]:
import numpy as np

## 2. Vector and Matrix Initializations

Just run these cells, and pay attention to shapes of arrays and reshape function. <br>
Notice the shape (n,) which is different than (n,1)

In [19]:
# vector
a_3_ = np.array([1,2,3]) 
print("a_3_:", a_3_.shape, a_3_)
b_12_ = np.arange(12)
print("b_12_:",b_12_.shape, b_12_)

b_1_12 = b_12_.reshape(1,12)
print("b_1_12:",b_1_12.shape, b_1_12)

b_12_1 = b_12_.reshape(12,1)
print("b_12_1:",b_12_1.shape, '\n', b_12_1)

a_3_: (3,) [1 2 3]
b_12_: (12,) [ 0  1  2  3  4  5  6  7  8  9 10 11]
b_1_12: (1, 12) [[ 0  1  2  3  4  5  6  7  8  9 10 11]]
b_12_1: (12, 1) 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [9]:
# matrix
c_2_2 = np.array([[1, 2], [3, 4]])
print("c_2_2:", c_2_2.shape, '\n', c_2_2)

b_3_4 = np.arange(12).reshape(3,4)
print("b_3_4:", b_3_4.shape, '\n', b_3_4)


c_2_2: (2, 2) 
 [[1 2]
 [3 4]]
b_3_4: (3, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 2a. Other matrix types and initialisation methods

In [4]:
# zero vector and matrix
a = np.zeros(5)
b = np.zeros(5, dtype=int)
c = np.zeros((3,2))
print("a:")
print(a)
print("b:")
print(b)
print("c:")
print(c)

a:
[0. 0. 0. 0. 0.]
b:
[0 0 0 0 0]
c:
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
# One vector and matrix
a = np.ones(5)
b = np.ones(5, dtype=int)
c = np.ones((3,2))
print("a:")
print(a)
print("b:")
print(b)
print("c:")
print(c)

a:
[1. 1. 1. 1. 1.]
b:
[1 1 1 1 1]
c:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
# random matrix
a = np.random.rand(3,2)
print("a:")
print(a)

a:
[[0.29926207 0.87953573]
 [0.64987273 0.33211021]
 [0.9642428  0.71753377]]


In [7]:
# Diagonal matrix
a = np.arange(3)
print("a:")
print(a)
a = np.diag(a)
print("diag a:")
print(a)
a = np.diag((2,3,4))
print("a:")
print(a)
a = np.diag(a)
print("diag a:")
print(a)
b = np.eye(3, dtype=int) # scalar matrix
print("scalar matrix:")
print(b)
b = np.eye(2,3)
print("rectangular diagonal matrix:")
print(b)
b = np.diag(b)
print("diag value")
print(b)

a:
[0 1 2]
diag a:
[[0 0 0]
 [0 1 0]
 [0 0 2]]
a:
[[2 0 0]
 [0 3 0]
 [0 0 4]]
diag a:
[2 3 4]
scalar matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
rectangular diagonal matrix:
[[1. 0. 0.]
 [0. 1. 0.]]
diag value
[1. 1.]


## 3 Multiplication, Transpose and Inverse

Pay attention to different types of multiplications. <br>

Here is a nice summary: <br>

- " * " == np.multiply != np.dot != np.matmul == @
- " * " and np.multiply need np.sum to perform dot product. Not recommended for dot product or matrix multiplication.
- np.dot works for dot product and matrix multiplication. However, recommended to avoid using it for matrix multiplication due to the name.
- np.matmul and @ are the same thing, designed to perform matrix multiplication. @ is added to Python 3.5+ to give matrix multiplication its own infix.
- np.dot and np.matmul generally behave similarly other than 2 exceptions: 1) matmul doesn’t allow multiplication by scalar, 2) the calculation is done differently for N>2 dimesion. Check the documentation which one you intend to use.

[numpy matmul doc](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) <br>
https://mkang32.github.io/python/2020/08/30/numpy-matmul.html#:~:text=matmul%20and%20%40%20are%20the%20same,designed%20to%20perform%20matrix%20multiplication.


In [35]:

c_matmul = np.matmul(b_3_4,b_3_4.T)
print("a matmul b: ", c_matmul)

c_matmul1 = b_3_4 @ b_3_4.T
print("a matmul b: ", c_matmul1)

c_dot = np.dot(b_3_4,b_3_4.T)
print("a matmul b: ", c_dot)

c_mult = np.multiply(b_3_4,b_3_4)
print("a multiply b: ", c_mult)

c_mult1 = b_3_4 * b_3_4
print("a multiply b: ", c_mult1)

a matmul b:  [[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]
a matmul b:  [[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]
a matmul b:  [[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]
a multiply b:  [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
a multiply b:  [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


### 3a. Verification: $AI = A$

Please make a code which multiplies matrix A by its identity to verify that you get the same matrix A.
What if A is not square? Check if AI and IA is the same for non-square matrix. Remember that $$I_mA = AI_n$$ where A is (m x n) matrix, which means the identity matrix must be a square matrix (m x m) in the first case, and (n x n) in the second.

In [40]:
a = np.arange(6).reshape(2, 3)
print("a:")
print(a)
i = np.eye(3, dtype=int)
print("identity matrix:")
print(i)
b = a @ i[:3,:3]
print("a multiply identity matrix")
print(b)
b = i[:2,:2] @ a
print("i multiply by a matrix")
print(b)

a:
[[0 1 2]
 [3 4 5]]
identity matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
a multiply identity matrix
[[0 1 2]
 [3 4 5]]
i multiply by a matrix
[[0 1 2]
 [3 4 5]]


### 3b. Code the inverse of (2, 2) matrix 

Code inverse matrix manually using det A = ... equation)
Then code using np.inv, and verify it is the same result

In [48]:
a = np.array([[1, 2], [3, 4]])
print("a:")
print(a)

a_inv1 = 1/(a[0,0]*a[1,1]-a[0,1]*a[1,0]) * np.array([[a[1,1], -a[0,1]], [-a[1,0],a[0,0]]])
print(a_inv1)

a_inv2 = np.linalg.inv(a)
print(a_inv2)


a:
[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]


### 3c. Verification: $AA^{-1}=I$

Please code similar verification for inverse matrix

In [50]:
print(a, '\n', a @ a_inv1)
print(a, '\n', a @ a_inv2)


[[1 2]
 [3 4]] 
 [[1. 0.]
 [0. 1.]]
[[1 2]
 [3 4]] 
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
